# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 23:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='chain',
            table='chain',
        ),
        migrations.AlterModelTable(
            name='employee',
            table='employee',
        ),
        migrations.AlterModelTable(
            name='store',
            table='store',
        ),
    ]
