# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 23:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0002_auto_20170521_2317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['-number']},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['-number']},
        ),
    ]
